             QSYS/PGM
             QSYS/DCL   VAR(&PROFILE) TYPE(*CHAR) LEN(10)
             QSYS/RTVJOBA CURUSER(&PROFILE)
             QSYS/CALL  PGM(INVMGLR400/ASSETEDT) PARM('NEW' &PROFILE)
             QSYS/ENDPGM
