             QSYS/PGM   PARM(&AID)
             QSYS/DCL   VAR(&AID) TYPE(*CHAR) LEN(8)
             QSYS/DCL   VAR(&PROFILE) TYPE(*CHAR) LEN(10)
             QSYS/RTVJOBA CURUSER(&PROFILE)
             QSYS/CALL  PGM(INVMGLR400/ASSETEDT) PARM(&AID &PROFILE)
             QSYS/ENDPGM
